### PR TITLE
Optimise the creation of the filename

### PR DESCRIPTION
**Pull request by EimaKve**
Changes:
- Used `si_string_make_fmt` for the filename.
- Added a comment questioning if it’s worth getting tm memory’s  memory.

PS:  Did not test if this works or compiles as intended as I had to do this PR on mobile; it was painful).

### CODE REVIEW

**Comment by ColleagueRiley** [comment]
`si_string_make_fmt` doesn't work for some reason

However, your comment is a valid question and it's been taken in account.

I had tried to use `si_string_make_fmt` before but due to it not working correctly I did not use it. 

Should I keep this open until you fix `si_string_make_fmt` ?

**Comment by EimaMei** [comment]
Yeah keep it open til I fix it

**Comment by EimaMei** [comment]
it should work now?

**Comment by EimaMei** [comment]
kys :trolleybus:

**Pull request closed without merging**
